# Generated by Django 4.2.9 on 2026-03-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuday',
            options={'ordering': ['week', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='menuday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='menuday',
            name='is_eat_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuday',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuday',
            name='week',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='menuday',
            unique_together={('menu', 'day', 'week')},
        ),
    ]
